import type { Metadata } from "next";
import "./globals.css";
import { host_grotesk } from "@/components/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${host_grotesk.className} w-screen overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
