import type { Metadata } from "next";
import { Urbanist, Host_Grotesk } from "next/font/google";
import "./globals.css";

export const urbanist = Urbanist({
  subsets: ["latin"],
});

export const host_grotesk = Host_Grotesk({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${host_grotesk.className} w-screen overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
